o2o/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^partner/', include('partner.urls')),
    url(r'^search/', include('search.urls',namespace='search')),
    url(r'^', include('client.urls')),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import (searchposts)

urlpatterns = [
     url(r'^$', searchposts, name='searchposts'),
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.shortcuts import render
from django.db.models import Q
from partner.models import Partner

# Create your views here.
def searchposts(request):
    if request.method == 'GET':
        query= request.GET.get('q')

        # submitbutton= request.GET.get('submit')

        if query is not None:
            lookups= Q(name__icontains=query) | Q(address__icontains=query) | Q(image__icontains=query)

            results= Partner.objects.filter(lookups).distinct()

            context={'results': results,
            }

            return render(request, 'search.html', context)

        else:
            return render(request, 'search.html')

    else:
        return render(request, 'search.html')
        
                     # 'submitbutton': submitbutton

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta gttp-equiv="X-UA-Compatible" content="IE=11; IE=10; IE=8; IE=7; IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>{% block title %}sample{% endblock %}</title>
    <!-- <title /> -->
    <!-- {% load staticfiles %} -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href='{% static "css/lib/bootstrap.min.css" %}'> -->
    <link rel="stylesheet" href='{% static "css/base.css" %}'>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  </head>
  <body>
    {% block body %}{% endblock %}
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <!-- <script src='{% static "js/lib/bootstrap.min.js" %}'></script> -->
    <!-- modal 작동되지 않아 추가 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  </body>
  </html>

templates/edit_info.html
{% extends "base.html" %}
{% block title %}업체 정보 관리{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <p class="text-secondary">업체 정보를 수정해주세요!</p>
  <hr class="mb-4">
  <div class="row">
    <div class="col-sm-6 col-sm-3-offset">
      <form enctype="multipart/form-data" method="post" action="">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn-outline-info btn-block" type="submit">
          저장하기
        </button>
      </form>
    </div>
  </div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}사업자 페이지{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  {% if user.is_authenticated %}
    {% if user.partner %}
      <div>{{ user.username }}님 환영합니다!</div>
      <hr class="mb-4">
      <div class="row">
        <div class="col-sm-6 col-sm-3-offset">
          <table class="table table-borderless">
            <tbody>
              <tr>
                <th scope="row">가게 사진</th>
                <td><img style="max-width:100%;" src="{{ user.partner.image.url }}"></td>
              </tr>
              <tr>
                <th scope="row">가게 이름</th>
                <td>{{ user.partner.name }}</td>
              </tr>
              <tr>
                <th scope="row">연락처</th>
                <td>{{ user.partner.contact }}</td>
              </tr>
              <tr>
                <th scope="row">주소</th>
                <td>{{ user.partner.address }}</td>
              </tr>
              <tr>
                <th scope="row">가게 소개</th>
                <td>{{ user.partner.description }}</td>
              </tr>
            </tbody>
          </table>
          <a href="/partner/edit/">
            <button class="btn btn-outline-info btn-block" type="submit">업체 정보 수정</button>
          </a>
        </div>

      </div>
    {% elif user.client %}
    <div class="jumbotron">
      <h2 class="display-3">사업자 페이지입니다!</h2>
      <p class="h3">사업자 회원만 이용 가능합니다.</p>
      <hr class="my-4">
      <a class="btn btn-secondary" href="/partner/signup/" role="button">사업자 회원가입</a>
      <a class="btn btn-info" href="/partner/login/" role="button">사업자 로그인</a>
      <a href="/">고객용 페이지 가기</a>
    </div>
    {% else %}
      <p class="text-secondary">가게 정보를 입력해주세요!</p>
      <hr class="mb-4">
      <div class="row">
        <div class="col-sm-6 col-sm-3-offset">
          <form enctype="multipart/form-data" method="post" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-outline-info btn-block" type="submit">
              저장하기
            </button>
          </form>
        </div>
      </div>
    {% endif %}
  {% else %}
  <div class="jumbotron">
    <h2 class="display-3">사업자(Partner) 페이지입니다!</h2>
    <hr class="my-4">
    <h5>가게를 등록하시려면 로그인이 필요합니다.</h5>
    <a class="btn btn-info" href="/partner/login/" role="button">로그인</a>
    <a class="btn btn-secondary" href="/partner/signup/" role="button">회원가입</a>
    <a href="/">client 페이지 가기</a>
  </div>
  {% endif %}
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}로그인{% endblock %}
{% block body %}
<hr class="mb-4">
<div class="container">
  <form method="post" action="" class="form-signin">
    <h1 class="h3 mb-3 font-weight-normal">{% if is_client %}member login{% else %}partner member login{% endif %}</h1>
    <hr class="mb-4">
    {% csrf_token %}
    <input type="text" name="username" class="form-control" placeholder="ID" required="" autofocus="">
    <input type="password" name="password" class="form-control" placeholder="Password" required="">
    {{ error }}
    <button class="btn btn-lg btn-outline-info btn-block" type="submit">login</button>
    <div class="modal-footer">
      <p class="text-secondary">아직 회원이 아니신가요?</p>
      {% if is_client %}
      <a href="/signup/">
        <button type="button" class="btn btn-outline-secondary">회원가입</button>
      </a>
      {% else %}
      <a href="/partner/signup/">
        <button type="button" class="btn btn-outline-secondary">사업자 회원가입</button>
      </a>
      {% endif %}
    </div>
    <div class="modal-footer">
      {% if is_client %}
      <a href="/partner/login/">사업자 회원 로그인</a>
      {% endif %}
    </div>
    <!-- <p class="mt-5 mb-3 text-muted text-right">배달의 민족</p> -->
  </form>
</div>
{% endblock %}

templates/main.html
{% extends "base.html" %}
{% block title %}고객 페이지 메인{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  {% if user.is_authenticated %}
    {% for category in category_list %}
    <p class="text-secondary h3">{{ category }}입니다!</p>
    {% endfor %}
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
        {% for partner in partner_list %}
          <div class="col-sm-4">
            <a href="/{{ partner.id }}/"><img style="max-width:100%;" src="{{ partner.image.url }}"></a>
            <a href="/{{ partner.id }}/"><h4>{{ partner.name }}</h4></a>
            <p class="text-muted">{{ partner.address }}</p>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  {% else %}
    <div class="jumbotron">
      <p class="h3"><a href="/">고객(client page)</a>과 <a href="/partner/">사업자(partner page)</a>를 하나의 플랫폼에 모아놓은 서비스를 구현했습니다.</p>
      <hr class="my-4">
      <a class="btn btn-info" href="/login/" role="button">로그인</a>
      <a class="btn btn-secondary" href="/signup/" role="button">회원가입</a>
    </div>
    {% for category in category_list %}
    <p class="text-secondary h3">{{ category }}입니다!</p>
    {% endfor %}
    <hr class="mb-4">
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
        {% for partner in partner_list %}
          <div class="col-sm-4">
            <a href="/{{ partner.id }}/"><img style="max-width:100%;" src="{{ partner.image.url }}"></a>
            <a href="/{{ partner.id }}/"><h4>{{ partner.name }}</h4></a>
            <p class="text-muted">{{ partner.address }}</p>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
  {% endif %}
</div>
{% endblock %}

templates/menu_add.html
{% extends "base.html" %}
{% block title %}메뉴 리스트{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <p class="text-secondary">메뉴를 {% if replacement %}{{ replacement }}{% else %}추가{% endif %}해주세요!</p>
  <hr class="mb-4">
  <div class="col-sm-6 col-sm-3-offset">
    <form enctype="multipart/form-data" method="post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <button class="btn btn-outline-info btn-block" type="submit">{% if replacement %}{{ replacement }}{% else %}추가{% endif %}하기</button>
    </form>
  </div>
</div>
{% endblock %}

templates/menu_detail.html
{% extends "base.html" %}
{% block title %}메뉴 리스트{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <p class="text-secondary">{{ menu.name }} 메뉴의 상세정보</p>
  <hr class="mb-4">
  <div class="row">
    <div class="col-sm-6 col-sm-3-offset">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th scope="row">사진</th>
            <td><img style="max-width:100%;" src="{{ menu.image.url }}"></td>
          </tr>
          <tr>
            <th scope="row">이름</th>
            <td>{{ menu.name }}</td>
          </tr>
          <tr>
            <th scope="row">가격</th>
            <td>{{ menu.price }}</td>
          </tr>
          <tr>
            <th scope="row">소개</th>
            <td>{{ menu.description }}</td>
          </tr>
        </tbody>
      </table>
      <a href="/partner/menu/{{ menu.id }}/edit/">
        <button class="btn btn-info btn-lg btn-block" type="submit">메뉴 수정</button>
      </a>

      <!-- Button trigger modal -->
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#exampleModalCenter">
          <i class="far fa-2x fa-trash-alt"></i>
        </button>
      </div>
      <!-- Modal -->
      <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h4 class="modal-title" id="exampleModalCenterTitle">삭제 알람</h4>
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body">
              <h5>메뉴가 삭제되요. 정말 삭제하실건가요??</h5>
            </div>
            <div class="modal-footer">
              <a href="/partner/menu/{{ menu.id }}/delete/">
                <button type="button" class="btn btn-outline-danger">네</button>
              </a>
              <button type="button" class="btn btn-outline-secondary" data-dismiss="modal">아니요</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/navbar.html
{% if is_partner %}
<hr class="mb-4">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>Navbar Template · Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbars/">

  <!-- Bootstrap core CSS -->
  <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <style>
  .bd-placeholder-img {
    font-size: 1.125rem;
    text-anchor: middle;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
  }

  @media (min-width: 768px) {
    .bd-placeholder-img-lg {
      font-size: 3.5rem;
    }
  }
  </style>
  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
</head>
<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <div class="container">
    <h4><a class="navbar-brand text-info font-weight-bold" href="/partner/">사업자 page</a></h4>
    <div class="collapse navbar-collapse" id="navbarsExample07">
      <ul class="navbar-nav mr-auto">
        {% if user.is_authenticated %}
        <li class="nav-item active">
          <a class="nav-link" href="/partner/menu/">메뉴관리</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/partner/order/">주문관리</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/partner/logout/">logout</a>
        </li>
        {% else %}
        <li class="nav-item active">
          <a class="nav-link" href="/partner/login/">login</a>
        </li>
        {% endif %}
        <li class="nav-item active">
          <a class="nav-link" href="/">고객페이지</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

<hr class="mb-4">
{% else %}
<html lang="en"><head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Jekyll v3.8.5">
  <title>Navbar Template · Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/navbars/">

  <!-- Bootstrap core CSS -->
  <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      -ms-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>
  <!-- Custom styles for this template -->
  <link href="navbar.css" rel="stylesheet">
</head>
<body>

  <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-info">
    <div class="container">
      <a class="navbar-brand font-weight-bold h3" href="/">배달 서비스</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample07" aria-controls="navbarsExample07" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample07">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/?category=KR">
              <i class="fas fa-pepper-hot"> 한식 </i>
            <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/?category=WE">
              <i class="fas fa-pizza-slice"> 양식 </i>
            <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/?category=JP">
              <i class="fas fa-fish"> 일식 </i>
            <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/?category=DE">
              <i class="fas fa-ice-cream"> 디저트 </i>
            <span class="sr-only"></span></a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/?category={{ choice }}">아무거나골라줘! <span class="sr-only"></span></a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="dropdown07" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">my page</a>
            <div class="dropdown-menu" aria-labelledby="dropdown07">
              <a class="dropdown-item" href="/order/">주문내역</a>
              <a class="dropdown-item" href="/logout/">logout</a>
            </div>
          </li>
          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="/login/">login <span class="sr-only"></span></a>
          </li>
          {% endif %}
          <li class="nav-item active">
            <a class="nav-link" href="/partner/">사업자페이지<span class="sr-only"></span></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0" method="GET" action="{% url 'search:searchposts' %}" value="{{request.GET.q}}">
          <input name="q" class="form-control" value="{{request.GET.q}}" type="text" placeholder="가게 검색" aria-label="Search">
          <!-- <input type="submit" name="submit" value="Search"/> -->
        </form>
      </div>
    </div>
  </nav>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>

</body></html>

{% endif %}

templates/order_list_for_client.html
{% extends "base.html" %}
{% block title %}메뉴 리스트{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <h2>주문입니다!</h2>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">주문시각</th>
        <th scope="col">가게 이름</th>
        <th scope="col">가게 전화번호</th>
        <th scope="col">요청사항</th>
        <th scope="col">주문 메뉴</th>
        <th scope="col">수량</th>
      </tr>
    </thead>
    {% regroup item_list by name as grouped %}
    {% for group in grouped %}
    {% for item in group.list %}
    <tbody>
      <tr>
        {% ifchanged %}<td rowspan="{{ group.list|length }}">{{ item.order.created_at }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.partner.name }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.partner.contact }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.requestment }}</td>{% else %}<td></td>{% endifchanged %}
        <td>{{ item.menu.name }}</td>
        <td>{{ item.count }}</td>
      </tr>
    </tbody>
    {% endfor %}
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/order_list_for_partner.html
{% extends "base.html" %}
{% block title %}메뉴 리스트{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <h2>주문입니다!</h2>
  <table class="table table-sm">
    <thead>
      <tr>
        <th scope="col">주문시각</th>
        <th scope="col">고객 ID</th>
        <th scope="col">전화번호</th>
        <th scope="col">주소</th>
        <th scope="col">요청사항</th>
        <th scope="col">주문 메뉴</th>
        <th scope="col">수량</th>
      </tr>
    </thead>
    {% regroup item_list by name as grouped %}
    {% for group in grouped %}
    {% for item in group.list %}
    <tbody>
      <tr>
        {% ifchanged %}<td rowspan="{{ group.list|length }}">{{ item.order.created_at }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.client.name }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.contact }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.address }}</td>{% else %}<td></td>{% endifchanged %}
        {% ifchanged item.order.created_at %}<td rowspan="{{ group.list|length }}">{{ item.order.requestment }}</td>{% else %}<td></td>{% endifchanged %}
        <td>{{ item.menu.name }}</td>
        <td>{{ item.count }}</td>
      </tr>
    </tbody>
    {% endfor %}
    {% endfor %}
  </table>
</div>
{% endblock %}

templates/order_menu_list.html
{% extends "base.html" %}
{% block title %}메뉴 리스트{% endblock %}
{% block body %}
{% include "navbar.html" %}
<div class="container">
  <p class="h4 text-secondary">{{ partner.name }} 메뉴입니다!</p>
  <hr class="mb-4">
  <div class="col-sm-6 col-sm-3-offset">
    <form method="post" action="">
    {% csrf_token %}
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col">메뉴 사진</th>
            <th scope="col">이름</th>
            <th scope="col">가격</th>
            <th scope="col">메뉴 소개</th>
            <th scope="col">수량</th>
          </tr>
        </thead>
        <tbody>
          {% for menu in menu_list %}
          <tr>
            <td><img style="max-width:150px;" src="{{ menu.image.url }}"></td>
            <td>{{ menu.name }}</td>
            <td>{{ menu.price }}</td>
            <td>{{ menu.description }}</td>
            <td><input style="width:40px; font-size:15px;" name="{{ menu.id }}" type="number" value=0 min=0 max=100 /></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      <p>
        <button class="btn btn-light btn-block btn-lg" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
          메뉴 주문
        </button>
      </p>
      <div class="collapse" id="collapseExample">
        <div class="card card-body">
          <div class="form-group">
            <label>전화번호</label>
            <input type="text" name="contact" class="form-control" placeholder="010-1234-1234" required="" autofocus="">
          </div>

          <div class="form-group">
            <label>배달 받을 주소</label>
            <input type="text" name="address" class="form-control" placeholder="서울 강동구 암사동 배달아파트" required="">
          </div>

          <div class="form-group">
            <label>요청사항</label>
            <input type="text" name="requestment" class="form-control" placeholder="선택사항">
          </div>

        </div>
        <button class="btn btn-info btn-block btn-lg" type="submit">주문하기</button>
      </div>
    </form>
    <hr class="mb-4">
  </div>
</div>
{% endblock %}

templates/search.html
{% extends "base.html" %}
{% block title %}회원가입{% endblock %}
{% block body %}
{% include "navbar.html" %}
<!-- <h1>Search Page</h1> -->

<!-- <br/> -->
<!-- <form action="{% url 'search:searchposts' %}" method="GET" value="{{request.GET.q}}">
Search <input type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts"/>
<input type="submit" name="submit" value="Search"/>
</form> -->

<div class="container">
  <hr class="mb-4">

{% if request.GET.q != '' %}
{% if results %}
<h3>"<b>{{ request.GET.q }}</b>" 검색결과 :</h3>
<br/><br/>

  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="row">
      {% for result in results %}
        <div class="col-sm-4">
          <a href="/{{ result.id }}/"><img style="max-width:100%;" src="{{result.image.url}}"></a>
          <br/>
          <a href="/{{ result.id }}/"><h4>{{result.name}}</h4></a>
          <br/>
          <p class="text-muted">{{result.address}}</p>
          <br/>
        </div>
      {% endfor %}
      </div>
    </div>
  </div>
{% else %}
<h3>일치하는 가게 이름이나 주소가 없습니다!</h3>
{% endif %}
{% endif %}
</div>
{% endblock %}

templates/signup_cong.html
{% extends "base.html" %}
{% block title %}회원가입 축하{% endblock %}
{% block body %}
<hr class="mb-4">
<div class="container">
  <div class="jumbotron">
    <p class="h3 font-weight-bold">회원가입을 축하합니다!</p>
    <hr class="my-4">
    <h5>서비스를 이용하시려면 로그인이 필요합니다.</h5>
    <hr class="mb-4">
    <a class="btn btn-outline-info btn-lg" href="/login/" role="button">고객 회원 로그인</a>
    <a class="btn btn-outline-info btn-lg" href="/partner/login/" role="button">사업자 회원 로그인</a>
  </div>
</div>
{% endblock %}